[project]
name = "isd-lite-data"
version = "0.1.0"
description = "A toolkit for accessing, downloading, and processing ISD Lite data"
authors = [
    { name="Jan Kazil", email="jan.kazil.dev@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "requests",
    "pandas"
]
