[project]
name = "isd-lite-data"
version = "1.1.1"
description = "A toolkit for accessing, downloading, and processing ISD Lite data"
authors = [
    { name="Jan Kazil", email="jan.kazil.dev@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "requests",
    "pandas"
    "xarray"
    "numpy"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


