'''
This script demonstrates how to load ISD-Lite observations for a set of
stations from previously downloaded local NCEI ISD-Lite files, aggregate them
into an xarray dataset, and save them to a NetCDF file for further analysis.

Workflow:
1. Defines the data directory where station metadata and observations are stored.
2. Loads station metadata from a text file previously generated by
   CONUS_Metadata_Download.py.
3. Loads observations for the specified year range from gzipped ISD-Lite files
   previously downloaded using CONUS_Observations_Download.py.
4. Populates the `Stations.observations` xarray dataset with the loaded data.
5. Adds descriptive metadata to the observations dataset.
6. Saves the dataset as a NetCDF file for efficient storage and downstream usage.

Inputs:
    - A station metadata text file named:
        conus_stations.<start_year>-<end_year>.txt
      located in the data directory.
    - Local gzipped ISD-Lite observation files for all stations in the metadata file.

Outputs:
    - A NetCDF file named:
        conus_stations.<start_year>-<end_year>.nc
      saved in the same data directory.

Example:
    Run this script after executing CONUS_Metadata_Download.py and
    CONUS_Observations_Download.py for the desired date range. The resulting
    NetCDF file can be used in xarray-based analysis workflows.
'''

from datetime import datetime
from pathlib import Path

from isd_lite_data import stations

#
# Directory where data are located/will be placed
#

data_dir = Path('..') / 'data'

#
# Load metadata from local file (must have been previously downloaded using CONUS_Metadata_Download.py)
#

start_year = 2020
end_year = 2020

start_date = datetime(start_year, 1, 1)
end_date = datetime(end_year, 12, 31)

file_name = 'conus_stations.' + str(start_date.year) + '-' + str(end_date.year) + '.txt'

file_path = data_dir / file_name

conus_stations = stations.Stations.from_file(file_path)

#
# Load observations from local files (must have been previously downloaded using CONUS_Observations_Download.py)
#

conus_stations.load_observations(data_dir, start_year, end_year, verbose=True)

conus_stations.observations.attrs['region'] = 'Contiguous US'

#
# Save observations as netCDF file
#

nc_file_name = 'conus_stations.' + str(start_date.year) + '-' + str(end_date.year) + '.nc'

nc_file_path = data_dir / nc_file_name

conus_stations.write_observations2netcdf(nc_file_path)
